[tool.poetry]
name = "winner-prediction"
version = "0.1.0"
description = "fotmob base의 축구 승부 예측"
authors = ["Joon <kkkths@naver.com>"]
readme = "README.md"
packages = [
    {include = "server", from = "."},
    {include = "client", from = "."}
]

[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.25.0"
pydantic-settings = "^2.12.0"
playwright = "^1.56.0"
sqlalchemy = "^2.0.23"
sqlmodel = "^0.0.14"
psycopg = {version = "^3.1.12", extras = ["binary"]}
asyncpg = "^0.29.0"
alembic = "^1.17.2"
scikit-learn = "^1.7.2"
fastapi = "^0.135.2"
uvicorn = {extras = ["standard"], version = "^0.42.0"}

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
